---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgB7IMkyySM89B9/T7fZkDIMRkV8m1pPJ/lIjzXmkdWVSk8JwohF9kPYz7iwZ98KMD44HiL8qUOYkR+SELh4M57ADaeFInVbXKI6bNWXfqUH0yeOMKvw5OavsDTFzCEQwpcYXBuFP63BFjfeW6LQlxa7o5TH/P2qgqSki27hgKm1BDBUaeV+polkpwXjaQt82nj+zkqgiAewugyAuHnSskRIzYeK6h++wwlwgu5Eq987SDAaI/uOvKJlQZid0u+ShCERYi6bhf8/9Hvgs6BtRTxSYFXMPoq+wb8P2RyndK5hRVeCP9XHLGIRZAmcZ5ctiTinG36DSQRDl6Q/xrtLTersxZG0ZpsIfdKwzT2US4k9mzHduHBeFtW404lOx6K0d/aOmGtao1Dtc0SnSkHI+9oRfNOGuRPNugD7/CxYOjmuKNpXeCuh7ZRGZOEEm1qqB8hzJs21dPGX7xrLtDaEh7SJ71cDptXPoHddQ/SeOdSMNtkEDaWodPjwesX/seRlmoawF9KCKj8IHvMoKWict2x0Jc1rv5YRxMaaRz4rshziDwwyNpm4rNgmh6UbNdJEJLWS/qIuBX+oZ3bC3EhbxI+yY7Ol2/OsWfZVKJmD8W0lmx1ml5JedU35pAOuA7j4O4CkWQl/r3hMA9daskBVLmqALSINttlU3K+18Nz+I033dcf3k4Gm29+YRqkLxvhWAhqU+ya1dLFgckelyOHyxlFVIFIPzmJ/I2bYHj0ihttoSD2ugUEKeSWlalTvnA3TvXN6XyP/rIFSG0oEMuqrIijyg80qDhPhT11IsjfFa8340ofcLd/YnXcCEXReGbIu5XOGNEZ0hNQ+3ztE1pf/5oHvXfkpCQY=
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
