---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgCltsBGj1Ecs9TNj66NveWRtnKEaSJzrXXm5MR7arfLkXHo2lrYN7L0Eqwy18zusI3z2SAUPlKjUROM39kHNrEOB9fc1eTmpnat03Yyje4+RIBpyZ7OcWQS3gZNJZ9pg5Wb76LTug3XB2qyOEZZmOV2HL/Bl5hJ+XPhz1D9L5BRlUpn2gkDJTUh1E1MExJQAq1znUixVmWY7au9HuddBesgDjV1SIjBpjjMp7lDF6IlSEjDibHA/4lJRQC2hnGHWNolc39zswunyWUveMyVWvgaR15OtRcG+6VaEAEMSTCvUvBC04EcvYjB0t1pn+v/p0VVId2+vEBI6dIhlQGvqWxNVQ++cItL2JkU7s43+0UKTgvJCdPPWvgm13+Nl/aHdjsCVkNA8lZdJ7InKAnZUh9azVe1pVt4bwC6OBCB1D/H5HelOkrnRTHJwAFZPoIjnJiOLIQyN9KAWRvn0OSMPaXoCgDMCuNZD4/SsNy4jy4j3GnanlOZa5oAAN9SGhfW2LGf2ejjvY4rFvVHYtye6kcLJgus1y+vmsZOxxmlBObpV0mALjjkZS23yB6SFioqs/IxDkXKOJwDSXBTJ6LvZ6gkhwTqLyp0oCHp4XNJ7+ih6UIT2v1i+XcAhNujQnAqw5HEj1iWJrQ9GnHIf0Eur5TfeDOAwU9uBPq33rN/sVjJeGL7ElvefHul+pDHDqR09N0sMAdavF26DNIZG2JzwJnD
    secretkey: AgBRM8xSirTHJkmx8TMGT29HhrlXFvzFiR9j39LqS3C/d46669yilUJ0nYb0NMmTLx03xKIYLpfx3l6a00CwqERIr9Td2SpbADhoinQ/Ur9ap8xChyayvg1kvnPfehu6Ogg1JctkJ/LQ/LJDOISUeWphM0zclBfEuJTF50HiniZdH8qudzam0YwGdnpjnhvwHOm4JeXDRRP8se8HJVIxSWMg+T5j6kp92JZ+D0o332yqf4S4DZJSe10luKXfKfbXOxIP/c4q9dVQwD/PCZwPzU3Ooic+98/S6BGCQuf48FJylzosqtbKkzsOzd2rIyPX9gSJ9ntnevPJDaTpEK3OuV1DOjiRpTyERWA/8OM685lyoDgRcJICs3MY4047+vMTYi4Z0fL4EXQzIQQt/Nqo81F5dRvJgOIuAeHRYmyWNpcjzQfwe9vdPn6bXrRrlz8LGAfp6P1pr/eBc1Kd8RSWl756gslFb4yDAy11A5K8RH+4eq3IA743Y0mvKmFi6/DHxHCMeGhUSlbGVX23+0K8nyHes//XPHeBP6kz2u+046xKwfRQdzVbf1zkwQdtDF4zY3Ny3rACMpeLLwQ0BxhPTjJ7jUlvwPU99EZmzSPX4LTNV++y3C3d4LK6YNaTxkPTesylV1D5QXbkHjbpEZaiSTM9lZYyWz3W/eWpEuMrHmpCwhuECmlL7J/VdEN2aWmMCDZYj6BlV6AxvIDKXe4lRE/AOXEGo3QLpBqpiEY=
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
