---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgA/w57217wG0JrwOyUWda9MoNBxMgZlxLo1uQaFzowdnf3hH7cXBQlY6jopdXH1omE0YeI46eFBlBlMhWnL2D/KMK+zGHWzAb8EhltuC9z7b3AzgxpeAO26837AsE3jkThm3tU4IvKtx5ijt4G/+puLxLOOvCY/8jQCbHjJqsClnAxzR/WlVf9FQOUpeKTnEPQRRByD+/28AeJ9qFer6iFkGZMs+IW1U5oLRDxUOKPnYfx2u4UtHB9qqJq1kjoO7b+HJNYmVVWnxTLxlvXRPsTXAKCXz8K8x7xRrx8UIf0somUYq2UJXCJ8AL8vZWVI5L3zFedeYUIDAVUoUOwsI70p4y3GuXPkCDSEQ/VxwjCHu2rp5MS7aolWRlD7MeeY4gfWvBm+6soDiyuLiw8ghTRtUzcWmIJEnGWLT2xIGIE2CI1CT0FP5Tjlx21DxAkdCvrCYfVzSwvd5ku8qgE6kgmc8rARInmOIQlEjarlPknm525i0p3/QZGRYkchURt3x9jAYgGR6PD/+yosL4Gb3nqBdREj+GzcCuA0gsURtIYEdc+xBicD2o8oxlRarxyPgMd2P+lsN5449lQXNwbw/zrrFxOBSXLylxVp3w1J2YzgSp1QBZhfhzSg11bGRFYhNv0ZEoM1rYwcwRkKEwjygPrIPqDhliE6kdTPk/JHodZqq99kMSIHUFvAG+zGkfR6Z1jICVG5VowpQU0Tis5zloJAp3wpQvVrC2OL50ip0FLua5SFRYqYRFne5+19R4oXEuBcPCdeoez5n0DJelHRjE7L1mPNz54qM5pqGA1yvEsr/sHRMghn5t/2rDhB77nP63iB8Imk8kjWOFjdsrLBwzlxzzrTwNVmh84tOuBAdJNcK1Fvzwp2aw==
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
