---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgCk9Bc7RCkpXEJMmTTb23zQ0CxJ0M/7+AfydglBxpS2uqhjuCthdw3QCk+ozJi62FzBi4bZWE2TEf6JapEPeJ5fy6M59Rxxo5c6AcROifiUeYU6y9gFk/IYZf/O9ZM2rwy1LWBY9ZTKRinoz4bWslLc1p9t9LsKnT3YvCehs0Bj33ywO6zPo/XwnzycyY+ESQFlt8fkgK+/AANXYlmWL+qu9o0wFNJ9IKFvpbYBsHGVSQEGnuutPCgP6zJVMuSiSl9MzFIQsO0syvDUqjnjIIeIU/ualJB88aM3BzAqNxN1QVxOOAFaMi+8uhKAlHUKdUgFbiOHGGvIO96g/wEFBTOebJLaQEkk912I7R5jncAdr+cQXNRcIzeKrdGnb9CSbx1GgizB4qkPfDoeHFjfEjnAq//C/BaWr3pIqunkalY8QSsMJ74rmUA0AzwF3kEnY9mmMIZkfai58CfogH2tpQVkfLSayIgjJyB96Ohzp0icitBTR529eK+27DSMBkm6495TwzhhhOkqVr1oe+TkxzjBEYI7If0FD/B8MMsEJkikHqhEX5zUGmTX/aFc1ckBZuoiRVbbn5eIo1V+JYaiL41bJSRWZkQMnL1K0iac+qyXr40rVgBmlAdAWiTAhdSl6ZH3sZSUhbxRWjKOAsYIertymI9JVkfGdB0lR8irvumSSczI/Hbz2QKl5prgSESlcx00Rlxvklwv3t2tuZ4AEegK
    secretkey: AgC10vvKJk8SYNQUs8QqEVQuiv7eOE+NsZDpoRrOsdXLBmifRU4607tVCwQVqIBKKk891AzB6vX4NgiZd5UdGmAk6FtJ703z3dO3TOlRGNylKNV/QA7oY8KBBpQaTZltqd8XjgTdIcsh2I9MbiizZIWVVP7/F3ty3E6AHMqsMVycvk/D508Wdadb3ChIA0e5NkzeBSBn+XA2K5uzgtaaFkuXPMf8uXckwhE/ghu+aHs8XSwomtBqZ+M7xleVEyii8VxWNk1urO5OLWXOfzdd6lGs3KvrQ1EGc32YJ08RPdtKNLTGmugqZdQF1ei/60nrpPDWftE6upsAqpIKPuq1NwjShdBxC15CloE1yzq203Pd/0XiWj9aJwdHx+DCHC0yquTyAsgmVmrl5yKGVC0EpYfCx5nLWKDTERGx/K3vqhT0rXvMT9W18xzn2NUzkB2/dtqdlBeYlcOEhpOPsmnM2BVU5b3lUsPZzm3+gni+rd7dfl/ks4AD1OjuTA6kKY8g26TZT560DHC3uo2s3kb+pTL2yGzO6alRBVgurCVk5cTOAkzPEVvk/6qDc5XadIkPS3UfM9itZBhUUnAKjOaN4ncMi8WQTNsNAO0PEFlsGKml+YZLA5ocYjuuXLxYZN/09NhDg/PH7AUCeCiANGVDxcSbl4CXnbT4dPaJolbGuTVxiatzQfigmYLyS8CmjqkBr+QE0dhA4z1bKyjxLYcbModfZQ==
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
