---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgCzT5zTSlL88bvSD9M3EnVMpalHpnn6sybvMwTipxKAvswIEi6p3EzoSdlRlLfDIi4hMxWTXIxKP9g51589pifFGdWySpf2MwHjtd2Qq8yLuD2rsOBOS7GQL6seWhZid44eEOqvy42aWcEW+13+l7ErR1D7dEDdkZv+leqCfu+JM77ZTbOp33x1PHEUgpgMp8RqKECPhmqn4eLV/16Iy3ynu9C1q1wMK7jFfJi+PwTf+0OvyULW8hbMgbVAhKV6MoPd/99ekmnKvJIlRjHV1l5g4/gnDnSdw/tVoJrsxTgSaFkaGeTpO+YpjoT0Cy2iN+jcP4v42V9424uRMjm3t4rFhd33LTHWZG9LTxr/aRq5lWM3jrBwMpG+bxsjyLIukNuSlWFR4UbbnKoY/83aG5Z5iUqLFEvJRONVCqeqou+1fa1hOK03l0tU77WytVD5NnVr4CPOKuA5szrgGbCbXX/vuU2tFFhejzw0gMtk4HnYXuwHgpoLz3VhiL87DLuWQpuQMtUSzPWoopNJvF5Pg+OSNZe+cRTkdU90JPC9pwPNVSQdmHb3JxBp2Eec5Pm3S6Hvv+uRfBOOXbo8c+x/3oaaeQz+6l7jBQ7Bco7o8GydV/lRQaloRPNwjYCOkxQZhAE+KmMY8rO0ZZBTfNJU2imx0JaLN1EPbh5vESBi9cz3RguJNeHQXX0Zi/nLs6pJ3IYLCJ3xncfaoW97QSWP
    postgres-password: AgAB46aXlz0x6LyqDqws91t4A1GjEVNGPWltzv40LD4tIXc8zqwDrJSggar3TzId4XaTMrynQ1CLU9Ay61Y5ki6PHAU2HUIxSG6lqXSdRCdYtPvPqt7Lk96uVvc0xWhoT0XCv1P53OHqF6V/oNErhu8WzuOGEfp0GEu/AuVY6QYPxiGtDsllSQb+3rsiXqf3xUEBnV4xw6EddvYgPs1JsNUroEGSSgRZUYpf1o+SA0kL2bnQI0O0FoKlPU5aL+Qi4sRmIhBW8JGDndh5ufmbAMVu70dfYp6nU/IzMJkVyTVTMtZlA/8OeD4zNvUxtOq/RyXiXlxDJFKuc9s7TlSHv15Btoi8j/vc1WyPBgSot1qkzOkP/Qaw6qvIDTqKipTxfMGY7HAZJolQtGtD1lZOyboPBiLphoeUX7CAUh6JCa9D4HIIROabBlDvK2OYMm0H7qnUoqEOISY5M/nx26kOUpKiOFSkXz41mL6dMXUCpZYDpohz2w0F1Vt2fe6uWhjXok07shDi6CHUlKeMK/n28M4Frb+V6yTJZwl2kpF30J/S1c07x9u+WASpQ5aJYXZcjGyHS9YoDbjdxEsjuFVxF6PMJQ2SZZBuqFiViW3/8UK/ZtAHwoi/ZvxLY2UUPutCNLfh/0tt83kyGqIS/sOAR/yllW2BQQ6mNXnNN1JsNrGOLnWo0YdwIe5VtlAB8yjAIZOrPlyXfFnsQ+XE70LC
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
