---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgAKAvXMVamwIyXj93bZayZwadc2pIt2Q8JKQ4SYDkENTDUlLJNfGAd8t2lImnB5f+xsj4OEKVYUkEXl/98JmhG/s7ArcO7nkv22l2Z2WIw9QJ9vkL07+lPufCj0NGrHxuNf0PeGodBwdQGXLx7fKjs4knf7kJymuw9f4TmB5PkX2BAYouNsiGlPc6IIxKxaucj2/EM5Kh5KDLC6itxYHUHmGhPk+sAtA1meBwAx5MbpHMcDivopnOCrJ/UDk9k0+iVbM76PyxVndT4v8bY2DuJ+J+fXN5oQq+2BQyhK83x5dfe102wSYm2cWY/bycfuhTrPN/qLBWlAHE2x+kMrPbWktQl2tg610KjF8aGbLPqgow+a6ooxaxJv7sEJ9sdlDEmRL90h2mj1JNWBg+ztZJZHB5BtsUyE42/LAzwZ/5H1qA3CC/RFsiH0Aeb7Rq7Jm4LQ8Evg9tvn20DZ0fwZ4MUJB4lXKEi7dSHvfo5xqT3ELbhM59w6/33zAluiI69zdO6mZKmnr3nYg08Bjc3xvwpYWZOc93lp9rzFEXg+OflvP9DdkQ8Vnd8Jz81nnIiflSfaaa0zxG+YL7kpA7uLoEDt4rHnhPgohi0SIDwLJ5RojhsqXqGaFA220zIN9Etm/XnxwgCqvCrzVOtNTo+doP+J1pxz8/+z9TAqq1kL9pZRuR/vWav/25dqWSo5graYIfqkjN/wWUbeG4PJgH3Ii2WKle44jRJHEHuGMfZ6uho=
    postgres-password: AgAfWutUfruURqrNQlf2dhHmDzXFa7MMgh8OofZq0lKuiz/1D/ymBx0QxYj6ZZW+u+GXi5ufJYf0zsb6v91T7MKT0vga93pXK0w9c2Faldgi6hBd1kSl2INWklryGon2bM2vzaN/ndZXrstqttNvgj77qraqlZVd4RVOJvcC0oLwKIUibgQJdtaOeYlH/+wCU8Pl1QUavyI92WTlQClTCdaJ2gDTi+HFEF+2CarAJHKCaCI4RwcY16uhWMScLA1hznYnaRoalC9/QzTLKs9xaP+JnBaPQrI0vvB+UTdE4Js7mnJe3CjhMpp/as8YMK3397XB0HnDFYbCcBXD85pzCapJFKFBJVrLIRCbuce0dm9LVDaXy6U6ZuLgE4tNfku9JhEm5B5NXD68fWjqJT/1kCh3SsqNbJR1agStMpUXaSjYYsT5OMNOetI578DnII6XeYZFlABQRODW3m+RpHXW/UrvWw6A1WBAGp6vU5jmFh/e+ZajL+Cohp7P7hnrNeBiAIndLqH74ySLh0cLH07t71AZ44cRfbC9AonXXb4tDVqgVSmWQOHzdK0GXL1jhCnn8ikjiEUFGDmGEgfyjr+gRG7mBiEJlVcIoAjYH/xNthvYHHoVcVdE382kYKAQrb/a8h1z4hwycf50JD5/vbKWWavVYonEcwmKWQNShxMkgXxjq/OXwpp3CGR+aPqt1+am0VDX7ZwHbL3J9bg6S9UN1/Qzy5BHplW0hY1l4dSS38c=
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
