---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-credentials
  namespace: mattermost
spec:
  encryptedData:
    DB_CONNECTION_STRING: AgAx0lbbbAX4GKcepiTfGoiAYqA1EzosJYmy5EvRAyCDskBzCUmjrqrA9lanPfRryrf5csxt1Q+sCSaA0BaNnu9q9BXPdQZbvVsKZoWBgjYNo4PrTAy+fFXeDWVlrb7e+G2YMTOqGONK0GXkJuuXbSVOHHZgdDZOzsRQwDEXDb6LOkOlnyT8mZ48Xd6VqtAH6ts9hGLJ8obEaEUHi9Uu3p1xByGfvx3hUBQBJynZBidvOVluqXitUOFxVkdQjDQng5OwbQcFltvEo9ks1rjNPCfluhrn30GTBthKxzysZiKj1+S/f+G10V2axs+c1omFjZ9keBZ+lHCQAT3QWqZoV6tmMIfCUn1i4LgGW05+c+3AyeVweWq40pYW8qGqPMbx604NW0K1secuI2xe1nHv+pv4rPDmLz5gsepB1RzKt8BXzGH7c/vXHwkT++1A6PnN3OhyxSlUwlQbmDx6bMVg6uXtl8C95RN1yT/ghFXMHZDDRm7DntkGWzVmWGOI0ZrTotxCS7CQXrDqMMfPiUfm3Qv2KJGYBQiz2dVG5ymFkw3CwDL7NNhyBmgr/AgTSW0AdYGIV3XAvUNc0kXB5F7gPrJHJYYEe4BkCSFh9FXbC/9qBjLxTw3ImlPPG/f3FVWcE8FT1prGgrNFeMrKN/sySsuKjNIrzELJ6Sp7VwZoAd6fvNV/XRI9SQ+901GfaTA10j5Rv6nBke62btYC9NggG0lsu9EoWOTCez6VUJpEAXmBGZz63ky7DRYZa42PbQ2te2QHDVzy9OnHKmQbotzMFQwXdN9H7bZ2Qq7kEE/D/v0ZKJBUCJT8A6EPhj7bR+iB+MBkMZ+3IpKK8SBt1xJZkz8IERPq+Uj2+fH+KKC5hbqA7nqaCD9UJg==
  template:
    metadata:
      name: mattermost-db-credentials
      namespace: mattermost
