---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-db-postgresql
  namespace: mattermost
spec:
  encryptedData:
    password: AgC0rfYWKb685ZoiKpjjeEkj3yb3H0VB8sIVtyPpdc5AXUD3zt51o2b/o4zKbPArHmyYRsuCtM4Ag7xp0anVIWYsx8538Vtymg3iY2jNYd4omeFNbco8Zr5aFCIMYTO+1tas+n27dwoC8E9wAcTSi8mMqbRDxhb2d6nGxK7W6g7b7mcYPQ77QW+g8n8pD2d8mnQu8CWLkWzf27CC7/WdlrwAO0VLTXl5y4lrDEACgDdaaRelXJCe9x//yodLUq6xDQUMDBEMZOvG+KGutgfrxytZqR0EtknxZdWmkpOJ5GRyAy0aXB3gRiKmAWwRnO5yLPkrW8p/N0fs+/TWYwmJ5hGVWa+dnoYUgZi3kGiVQfOO+6nrN0MBwEiIQZyJOXhKl5TU2tJk90FFjGHxJXC3bGIzdBd8LGbXNUESQszkYb3Qy4y5dYus2EyFR+bLLp3NDQKB7vU0p8QE+A8SWiQ/kIZDYfvNdX498LI9TK9+JUb2ZXQKRDAIEkX0NBXIaBTtLaA+5a5414qC0wnUOGgIHMYRcb2+c7WUnk2mlxHWRQlvmbj9ZAW8dL2kgYIHaM8MdRYZLRCSoon6+OSw2SkrhafJllkXTAkWFPIPd//L1Y4WN1QuPnyWkcxf/0QyozdPBmX4IgGz3BZTNH4flM/lRSsiHmSIQ+XXcQP8wJEx8L3T+4cDTLusxUVwpIrQayE/aukIOEUVFEnPwiBUOBV8
    postgres-password: AgBliX1pw8An6PhxWLaBiCfdM/r8bl3Vmo3RfLUMajYU3PyK0PFqzeuU+eUWHDtr77t8bzVCpfPXnzGjXeLh95tWE7NWyhGXmGXECbRZnoJ92Uc67Z0GgU5csd8zboban1C3Dc/XF5FL8LrFxbfOL5jSSg9yxg1o5iXCxwVIwTVvZmNZNrekZA6I5Eb7HYH0iYXJqpNzohC99cqdqMBUP39phX+1YsYiHAhR9ZUKzFsHlemeSGzCvSWYQFU/00tPQhpK68XBINdzkBZSnuoAKjtOqaxpH/AWQkVzxKAyIuIXkHkTcu006uOLOT4Ut6xh0FL5aQqvJtmITatTO5DNfCDtrJxxGgJ9MynqveDgmMVh6iwB8tEtmeZ/zNGQPH05TC9CXmgJPRwH1n+clMT5ZgQ5XDHg1fbtRi/mUvL1yFFsamcVpf2gymKSRORn8IIzpBoEEk84M48QnlDEkfbKP+P/tIKGeLwHgvO2tQabVrXdrrwLSqaVdBdtwBhwDaoZjB8tz04dCpGZBhVFi/nFPOVfhvPVPHhG8wfHGXQC4HQ1vD0weCn39hrkKXBd/ZLwGhfhzVp1Dbg3RV5VvuognZGYXh8bT9pY48KznxBvHOhyJVby9TSTxOW/pdSECYTpp13X6k8OVJ+BTbW680/bb6R4cvcxkAHZ3T0VznuAq31jrDmsjdc3gV408pKkEb4D7oCcSvw3W0xHkLc5fp2p
  template:
    metadata:
      name: mattermost-db-postgresql
      namespace: mattermost
