---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mattermost-minio-credentials
  namespace: mattermost
spec:
  encryptedData:
    accesskey: AgAMBH9OkrnTIu90w2O3o1OzzYZNa358u23pn/JeySMFbRkzYoaL8CaMlJPrmGvaxn+C8wn+kiwnt7VhmlubJW/YUAd3ZBDoGWTmNYZ/lW6iQc3+leFo3y02FCkoe1zWAFMdMkMPoVYCPtwqYElWmtu8oOsa+UGXF0i7O2IJoazKSVLW9NQp/4O3qkJm+cBm21LXB8cu6WfFtxvYuI9maZfX/yxViYCzi4BP/T4z3v6dVTrLfl/KWNSbBFQaSn2L9FFlpjk2qnn3DmU8dVWhQDDyCzZGprFsVq2org2Eey4qjg7Be/zKbYpjU+Q5+YNIdYqPIRquhKkNBwondlMGatsdver032HfjeFnhYg29ENZO0p464ibiSerSCd2Jd2V4yq3C0MKd748LVMuFq5CnNYHNzz60xrR0U3siW6gGRXjUWUG1jZskMvXU9XwgqPQjYSTIO8Trcc/5qcZnUbCVBb78Z1uMN6M4dfxoqCmyFF/XdPwIPPRTYuPXYDpUsOCEeNv0mKe/UXm5YpKFNrwshk9ZmcrtOfBhVxsKZLxwyfs/EbxooEfhzmf0Y3YNH09P4dC1ua0CO0HW9Tm0RvgAJPQ6S1AMIQvz7GrVzdIEXAR7bzPYdD2rGlfj89iWHqZL/Q/wtbtNHwdK19bFcrCMR8VZnHSOkDAnsulnBdXOHslxHr2e2U02WXdrb5qPjYoQr27fn9X7JPd5glWwzu7ABzl
    secretkey: AgA8wDjg44+x+6kC8N0Ml79Gj6mFbQgouj0WEEWq3DSO1VjPm/pErRFRvyb0VKrMdK2KJGxhf8dc1AP55RLa6OPB/G9kWRHgZ2AcXTML+ZiRJ2YlHQo7V3BE0o3w2xh54v9Gacg91Ith7OLXjaIxTg+zDFJcQzlWklgOIoI1jg4Pq8UYEgw3mquPqX/wvQRcM6zq7rVQpb6by6WIFAyo2RTjqpBEVowtKcMc/VVwyVsYJAErDduMtNI7E4bpQW0lcUlcEst3GeAVCjSF1YJEb5f+xOLzNkmqlUaukzRjv4kQQqD+YVAR90PoBGe8+2HzeRHrIdKN7quI7v1Fp6VjkvI5zAFgUxtgR0h9TRKL9O3qf2dahYeoFShJ40dE5mPw82xkitVDhMEmv74atixHiFgchaJKCWTteC7oTL3OBoLR6W80FNv5pNXO7BCNTXh7avxF7tU3wON4sot85b3f1VrIQbEwjqqUx1OgTub+CH1pb92Nyc1ScMvd/0N7E3ItGzUnGu6fvA98II83I2I/WHEIT8t8qCG5GcUdsQemkzLcAGKfifXzgPLuDprRXPXeR/aeVaMRgeBjwzmvLB/nsNeKHjFdveAGE+vgEY1VCcSB2p5g7GBNKmmCnKV1HrC2UlqM1I+ZR6Cgf4GluTBxbbAuzYUEHt6NZ3ps2hk2Em3MB3UhBK3asD2W0DF8xDJVzA+sdV5NOGtbeYqU0rznvFkmdw==
  template:
    metadata:
      name: mattermost-minio-credentials
      namespace: mattermost
